name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - uses: Xotabu4/selenoid-github-action@v2

      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Add .nojekyll file
        if: always()
        run: touch allure-history/.nojekyll

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true